Repository sparcs-kaist/new-ara-web, pull requests merged in 2019-11, with the labels that each got.

#93 Create .editorconfig
  .editorconfig
Labels: not important

#92 Preselect board from previous route.
  src/components/ThePostWrite.vue
Labels: advanced

#97 Fix 401 issue on safari.
  src/api/post.js
  src/store/auth.js
Labels: bug

#103 404 page
  src/App.vue
  src/http.js
  src/router/app.js
  src/theme.scss
  src/views/NotFound.vue
Labels: design

#110 [Issue #101] Placeholder for editor
  src/components/TheTextEditor.vue
Labels: hot fix
