Repository sparcs-kaist/new-ara-web, pull requests merged in 2023-07, with the labels that each got.

#385 Design: color
  public/index.html
  public/manifest.json
  src/components/SmallBoard.vue
  src/components/TheOrganizations.vue
  src/theme.scss
Labels: design

#389 Update all name_type functions
  README.md
  src/components/PostComment.vue
  src/components/PostCommentEditor.vue
  src/components/ThePostDetail.vue
  src/components/ThePostHeader.vue
  src/main.ts
  src/progressBar.js
  src/views/helper.js
Labels: bug

#392 Redesign alarm page
  src/api/user.js
  src/components/Notification.vue
  src/components/TheNotifications.vue
Labels: feature

#391 Feature/channeltalk
  .env.example
  .github/workflows/aws.yml
  .github/workflows/github-actions.sh
  Dockerfile
  src/App.vue
  src/channel.js
  src/components/TheFooter.vue
  src/views/Facade.vue
Labels: feature

#394 Fix channel plugin key
  .github/workflows/aws.yml
  Dockerfile
Labels: chore

#395 Open channel talk as a messenger
  src/components/TheFooter.vue
Labels: chore

#393 Update board fetching logic in global navigation bar
  src/api/board.js
  src/components/TheNavbar.vue
  src/store/index.js
Labels: backend
