Repository sparcs-kaist/new-ara-web, pull requests merged in 2024-03, with the labels that each got.

#435 [EKS] AWS S3 Deploy CI/CD
  .github/workflows/aws-s3.yml
  src/http.js
Labels: feature

#438 Fix deploy arguments
  .github/workflows/aws-s3.yml
  src/http.js
Labels: deploy

#439 fix(deploy): Fix wrong environ name
  .github/workflows/aws-s3.yml
Labels: deploy

#430 Bug/footer
  src/components/TermsPopup.vue
  src/components/TheFooter.vue
  src/router/auth.js
Labels: bug
